from __future__ import annotations

from pathlib import Path

from pistomp_recovery import audio_card
from pistomp_recovery.constants import BOOT_FIRMWARE_DIR, RECOVERY_DIR
from pistomp_recovery.file_facet import FileFacet, MissingFactoryBaseline, TrackedFile

BOOT_REPO: Path = Path(RECOVERY_DIR) / "system.git"


def _moved_boot_placeholder(text: str) -> bool:
    """Identify old-image stubs whose real files moved under /boot/firmware."""
    return text.startswith("DO NOT EDIT THIS FILE") and "has moved to /boot/firmware/" in text


BOOT_FILES: tuple[TrackedFile, ...] = (
    TrackedFile(
        "config.txt",
        Path(BOOT_FIRMWARE_DIR) / "config.txt",
        restore=audio_card.restore_config_txt,
        missing_factory_baseline=MissingFactoryBaseline.ADOPT_LIVE,
        factory_baseline_is_stale=_moved_boot_placeholder,
    ),
    TrackedFile(
        "cmdline.txt",
        Path(BOOT_FIRMWARE_DIR) / "cmdline.txt",
        missing_factory_baseline=MissingFactoryBaseline.ADOPT_LIVE,
        factory_baseline_is_stale=_moved_boot_placeholder,
    ),
    TrackedFile(
        "pistomp.conf",
        Path(BOOT_FIRMWARE_DIR) / "pistomp.conf",
        missing_factory_baseline=MissingFactoryBaseline.ADOPT_LIVE,
    ),
    TrackedFile(
        "jack",
        Path("/etc/default/jack"),
        missing_factory_baseline=MissingFactoryBaseline.ADOPT_LIVE,
    ),
    TrackedFile(
        "asound.state",
        Path("/var/lib/alsa/asound.state"),
        missing_factory_baseline=MissingFactoryBaseline.ADOPT_LIVE,
    ),
)


def make_boot_facet() -> FileFacet:
    """Return a boot FileFacet for registration by an entry point."""
    return FileFacet(name="boot", repo_dir=BOOT_REPO, files=BOOT_FILES)
