from __future__ import annotations

import logging
from pathlib import Path

from pistomp_recovery import audio_card, git_util
from pistomp_recovery.constants import BOOT_FIRMWARE_DIR, RECOVERY_DIR
from pistomp_recovery.facet import RollbackTarget
from pistomp_recovery.file_facet import FileFacet, TrackedFile

logger = logging.getLogger(__name__)

BOOT_REPO: Path = Path(RECOVERY_DIR) / "system.git"

CONFIG_TXT = "config.txt"

BOOT_FILES: tuple[TrackedFile, ...] = (
    TrackedFile(CONFIG_TXT, Path(BOOT_FIRMWARE_DIR) / "config.txt"),
    TrackedFile("cmdline.txt", Path(BOOT_FIRMWARE_DIR) / "cmdline.txt"),
    TrackedFile("pistomp.conf", Path(BOOT_FIRMWARE_DIR) / "pistomp.conf"),
    TrackedFile("jack", Path("/etc/default/jack")),
    TrackedFile("asound.state", Path("/var/lib/alsa/asound.state")),
)

# Recovery releases through 0.1.0-32 tracked /boot/config.txt and
# /boot/cmdline.txt, where the image writes a "moved to /boot/firmware"
# stub (pi-gen-pistomp stage1/00-boot-files/00-run.sh).  An upgraded device's
# factory branch therefore holds that stub where the real boot file belongs.
_STUBBED_BY_OLD_RELEASES: tuple[str, ...] = (CONFIG_TXT, "cmdline.txt")


def _is_moved_placeholder(text: str) -> bool:
    """Identify a /boot stub captured as a factory baseline by an old release."""
    return text.startswith("DO NOT EDIT THIS FILE") and "has moved to /boot/firmware/" in text


class BootFacet(FileFacet):
    """Boot files, plus the two rules that are specific to them.

    Factory reset keeps the audio card that is physically fitted, and factory
    baselines are adopted from the live file on devices whose repository was
    written by a recovery release that tracked different paths.
    """

    def _restore_to_live(self, file: TrackedFile, target: RollbackTarget) -> None:
        """
        Restore one boot file, keeping the fitted card on a factory reset.
        A checkpoint is a known-good device state and is restored exactly.
        A factory image is hardware-independent, so the currently selected card
        must be applied to it. If the live selection is ambiguous or the factory
        text has no line for it, leaving config.txt alone is safer than writing
        a config that may leave the device without audio.
        """
        restored = self._repo_path(file.name)
        if file.name != CONFIG_TXT or target != "factory" or not restored.exists():
            super()._restore_to_live(file, target)
            return

        try:
            fitted = audio_card.active_card(file.source.read_text())
            merged = audio_card.select_card(restored.read_text(), fitted) if fitted else None
        except (OSError, UnicodeDecodeError):
            logger.warning("cannot read %s as text; restoring it verbatim", file.name)
            super()._restore_to_live(file, target)
            return

        if merged is None:
            logger.warning("cannot identify the fitted audio card; leaving %s as-is", file.name)
            return
        file.source.write_text(merged)

    def _needs_factory_baseline(self, file: TrackedFile) -> bool:
        if not file.source.exists():
            return False
        if not self._exists_in_ref(file.name, git_util.FACTORY_BRANCH):
            return True
        if file.name not in _STUBBED_BY_OLD_RELEASES:
            return False
        factory = git_util.git("show", f"{git_util.FACTORY_BRANCH}:{file.name}", cwd=self.repo_dir)
        return _is_moved_placeholder(factory)

    def migrate_factory_baseline(self) -> None:
        """Adopt live baselines for files added or invalidated by an upgrade."""
        self.init_repo()
        migrations = [file for file in self.files if self._needs_factory_baseline(file)]
        if not migrations:
            return

        names = ", ".join(file.name for file in migrations)
        logger.info("seeding factory state for %s: %s", self.name, names)
        for file in migrations:
            self._copy_to_repo(file)
        git_util.add_and_commit(self.repo_dir, f"track new {self.name} files")
        git_util.git("checkout", git_util.FACTORY_BRANCH, cwd=self.repo_dir)
        for file in migrations:
            self._copy_to_repo(file)
        git_util.add_and_commit(self.repo_dir, f"seed factory {self.name} state")
        git_util.git("checkout", git_util.DEVICE_BRANCH, cwd=self.repo_dir)


def make_boot_facet() -> BootFacet:
    """Return a boot facet for registration by an entry point."""
    return BootFacet(name="boot", repo_dir=BOOT_REPO, files=BOOT_FILES)
